common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    # path('profile/<str:pk>', views.profile, name='profile'),
    # path('settings', views.settings, name='settings'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from Main import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    # 메인화면
    path("", views.index, name="index"),
    path("board/", views.board, name="board"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("answer/create/<int:question_id>/", views.answer_create, name="answer_create"),
    path("question/create/", views.question_create, name="question_create"),
    path("common/", include("common.urls")),
    path("diagnosis/", views.diagnosis, name="diagnosis"),
    # 진단 다운로드 페이지
    path("diagnosis/window", views.winsow_diagnosis, name="window_diagnosis"),
    path("diagnosis/linux", views.linux_diagnosis, name="linux_diagnosis"),
    # 질문답변 수정 및 삭제
    path(
        "question/modify/<int:question_id>/",
        views.question_modify,
        name="question_modify",
    ),
    path(
        "question/delete/<int:question_id>/",
        views.question_delete,
        name="question_delete",
    ),
    path("answer/modify/<int:answer_id>/", views.answer_modify, name="answer_modify"),
    path("answer/delete/<int:answer_id>/", views.answer_delete, name="answer_delete"),
    # 수동 업로드 페이지
    path("model_form/", views.model_form, name="model_form"),
    path("model_form_upload/", views.model_form_upload, name="model_form_upload"),
    path(
        "model_form_delete/<int:file_id>/",
        views.model_form_delete,
        name="model_form_delete",
    ),
    # 스크립트 실행
    path("connect/", views.connect, name="connect"),
    path("run_script/", views.run_script, name="run_script"),
    path("connect_user/", views.connect_user, name="connect_user"),
    path("connect_list/", views.connect_list, name="connect_list"),
    path(
        "connect_list_delete/<int:file_id>/",
        views.connect_list_delete,
        name="connect_list_delete",
    ),
    path("pyqt5/", views.pyqt5, name="pyqt5"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField()


class Document(models.Model):
    uploader = models.CharField(max_length=100)
    description1 = models.CharField(max_length=255, blank=True)
    description2 = models.CharField(max_length=255, blank=True)
    description3 = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to="documents/")
    uploaded_at = models.DateTimeField(auto_now_add=True)


class Autoupload(models.Model):
    user = models.CharField(max_length=100)
    file = models.FileField(upload_to="uploads/")
    create_date = models.DateTimeField(null=True, blank=True)


class UploadFiles(models.Model):
    _id = models.AutoField(primary_key=True)
    email = models.CharField(max_length=100)
    txt_file = models.FileField(upload_to="uploads/")
    xlsx_file = models.FileField(upload_to="uploads/")
    created_at = models.DateTimeField()
    AscorePer = models.DecimalField(max_digits=5, decimal_places=2)
    SscorePer = models.DecimalField(max_digits=5, decimal_places=2)
    PscorePer = models.DecimalField(max_digits=5, decimal_places=2)
    LscorePer = models.DecimalField(max_digits=5, decimal_places=2)
    SescorePer = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        db_table = "upload_files"

common/models.py
from django.db import models
from common.forms import UserForm

# Create your models here.

Main/forms.py
from django import forms
from .models import Question, Answer, Document, Autoupload


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ["subject", "content"]  # QuestionForm에서 사용할 Question 모델의 속성
        widgets = {
            "subject": forms.TextInput(attrs={"class": "form-control"}),
            "content": forms.Textarea(attrs={"class": "form-control", "rows": 10}),
        }
        labels = {
            "subject": "제목",
            "content": "내용",
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["content"]
        labels = {
            "content": "답변내용",
        }


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = [
            "uploader",
            "description1",
            "description2",
            "description3",
            "document",
        ]
        labels = {
            "uploader": "업로더",
            "description1": "항목1 점수",
            "description2": "항목2 점수",
            "description3": "항목3 점수",
            "document": "파일",
        }


class AutouploadForm(forms.ModelForm):
    class Meta:
        model = Autoupload
        fields = ["user", "file", "create_date"]
        labels = {"user": "유저", "file": "파일", "create_date": "날짜"}

Main/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Question, Answer, Document, Autoupload, UploadFiles
from .forms import QuestionForm, AnswerForm, DocumentForm, AutouploadForm

from django.utils import timezone
from django.http import HttpResponseNotAllowed
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.conf import settings
from django.core.files.storage import FileSystemStorage

from django.http import HttpResponse
import subprocess
import os
import datetime
import time
from django.core.files import File

from django.conf import settings
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile

# Create your views here.


def board(request):
    page = request.GET.get("page", "1")  # 페이지
    question_list = Question.objects.order_by("-create_date")
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {"question_list": page_obj}
    return render(request, "question_list.html", context)


def detail(request, question_id):
    question = Question.objects.get(id=question_id)
    context = {"question": question}
    return render(request, "question_detail.html", context)


@login_required(login_url="common:login")
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect("detail", question_id=question.id)
        else:
            form = AnswerForm()
        context = {"question": question, "form": form}
        return render(request, "question_detail.html", context)


@login_required(login_url="common:login")
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.save()
            return redirect("index")
    else:
        form = QuestionForm()
    context = {"form": form}
    return render(request, "question_form.html", context)


@login_required(login_url="common:login")
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, "수정권한이 없습니다")
        return redirect("detail", question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect("detail", question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {"form": form}
    return render(request, "question_form.html", context)


@login_required(login_url="common:login")
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, "삭제권한이 없습니다")
        return redirect("detail", question_id=question.id)
    question.delete()
    return redirect("index")


@login_required(login_url="common:login")
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, "수정권한이 없습니다")
        return redirect("detail", question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect("detail", question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {"answer": answer, "form": form}
    return render(request, "answer_form.html", context)


@login_required(login_url="common:login")
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, "삭제권한이 없습니다")
    else:
        answer.delete()
    return redirect("detail", question_id=answer.question.id)


def simple_upload(request):
    if request.method == "POST" and request.FILES["myfile"]:
        myfile = request.FILES["myfile"]
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(
            request, "simple_upload.html", {"uploaded_file_url": uploaded_file_url}
        )
    return render(request, "simple_upload.html")


def download(request):
    return render(request, "download.html")


# 수동 업로드 & 파일 관리


@login_required(login_url="common:login")
def model_form(request):
    documents = Document.objects.all()
    return render(
        request,
        "model_form.html",
        {
            "documents": documents,
        },
    )


@login_required(login_url="common:login")
def model_form_upload(request):
    if request.method == "POST":
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("model_form_upload")
    else:
        form = DocumentForm()
    return render(
        request,
        "model_form_upload.html",
        {
            "form": form,
        },
    )


def model_form_delete(request, file_id):
    model_delete = Document.objects.get(pk=file_id)
    model_delete.document.delete()  # 파일 삭제
    model_delete.delete()  # 모델 삭제
    return redirect("model_form")


# 진욱이 작업


def index(request):
    return render(request, "home.html")


def diagnosis(request):
    return render(request, "diagnosis.html")


def winsow_diagnosis(request):
    return render(request, "window_diagnosis.html")


def linux_diagnosis(request):
    return render(request, "linux_diagnosis.html")


# 스크립트 페이지


def run_script(request):
    subprocess.call(["python", "static/Syne.py"])
    return HttpResponse("Script executed successfully.")


@login_required(login_url="common:login")
def connect(request):
    return render(request, "connect.html")


def upload_report(request):
    user = request.user
    user_name = request.user.username  # 현재 로그인한 유저의 이름
    date = datetime.datetime.now().strftime("%Y-%m-%d")  # 현재 날짜
    folder_path = os.path.join(settings.MEDIA_ROOT, "newfile", user_name, date)

    # 파일 경로를 설정합니다.
    file_path = os.path.join(folder_path, "txt", "report.txt")  # 생성된 파일의 경로
    file_name = f"{user_name}_{date}_report.txt"  # 생성할 파일의 이름

    # 파일이 생성될 때까지 기다리는 함수
    def wait_for_file(file_path, timeout=20):
        start_time = time.time()
        while not os.path.exists(file_path):
            elapsed_time = time.time() - start_time
            if elapsed_time > timeout:
                raise TimeoutError(
                    f"File {file_path} was not created within the timeout."
                )
            time.sleep(0.1)

    wait_for_file(file_path)  # 파일이 생성될 때까지 대기합니다.

    file_obj = File(open(file_path, "rb"))

    # 모델 인스턴스를 생성하고 File 객체를 모델 필드에 할당합니다.
    my_model = Autoupload(user=user)
    my_model.file.save(file_name, file_obj, save=True)


def connect_user(request):
    if request.method == "POST":
        client_IP = request.POST.get("client_IP")
        client_name = request.POST.get("client_name")
        client_password = request.POST.get("client_password")

        user_name = request.user.username  # 현재 로그인한 유저의 이름
        date = datetime.datetime.now().strftime("%Y-%m-%d")  # 현재 날짜

        form = AutouploadForm(request.POST)

        # 폴더 경로를 생성합니다.
        folder_path = os.path.join(settings.MEDIA_ROOT, "newfile", user_name, date)
        os.makedirs(folder_path, exist_ok=True)
        os.environ["FOLDER_PATH"] = folder_path

        subprocess.call(
            [
                "python",
                "static/Syne.py",
                client_IP,
                client_name,
                client_password,
            ]
        )

        context = {
            "user_id": request.POST.get("user_id"),
            "agree": request.POST.get("agree"),
            "client_IP": request.POST.get("client_IP"),
            "client_name": request.POST.get("client_name"),
            "client_password": request.POST.get("client_password"),
            "form": form,
        }
        upload_report(request)
    return render(request, "connect_user.html", context)


@login_required(login_url="common:login")
def connect_list(request):
    items = Autoupload.objects.all()
    return render(
        request,
        "connect_list.html",
        {
            "items": items,
        },
    )


def connect_list_delete(request, file_id):
    list_delete = Autoupload.objects.get(pk=file_id)

    # Close the File object and delete the file.
    list_delete.file.close()
    file_path = os.path.join(settings.MEDIA_ROOT, list_delete.file.name)

    try:
        if os.path.isfile(file_path):
            os.remove(file_path)
    except PermissionError as e:
        print(f"Error: {e}")

    # Sleep for 3 seconds before attempting to delete the model.
    time.sleep(3)
    list_delete.delete()  # 모델 삭제

    return redirect("connect_list")


def pyqt5(request):
    items = UploadFiles.objects.all()
    return render(request, "pyqt5.html", {"items": items})

Main/templates/answer_form.html
{% extends 'base.html' %} {% block content %}
<!-- 답변 수정-->
<div class="container my-3">
  <form method="post">
    {% csrf_token %} {% include "form_errors.html" %}
    <div class="mb-3">
      <label for="content" class="form-label">답변내용</label>
      <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

Main/templates/connect_list.html
{% extends 'base.html' %} {% load static %} {% block content %}
<head>
  <style>
    .table {
      border: 3px solid black;
      width: 90%;
    }

    .table,
    #tex {
      margin: 10px 20px;
    }

    h2 {
      text-align: center;
    }
  </style>
</head>

<h2>{{ user.username }}'s AutoUpload File</h2>
<table class="table">
  <thead>
    <tr>
      <th>업로더</th>
      <!-- <th>파일</th> -->
      <th>다운로드</th>
      <th>파일 내용</th>
      <th>업로드 시각</th>
      <th>삭제</th>
    </tr>
  </thead>
  <tbody>
    {% for Autoupload in items %} {% if Autoupload.user == user.username %} {% load custom_filters %}
    <tr>
      <td>{{ Autoupload.user }}</td>
      <!-- <td>{{ Autoupload.file }}</td> -->
      <td>
        <a href="{{ Autoupload.file.url }}" class="btn btn-primary btn-sm">Download</a>
      </td>
      <td><pre>{{ Autoupload.file.read|decode_text:'ANSI' }}</pre></td>
      <td>{{ Autoupload.create_date }}</td>
      <td>
        <a href="{% url 'connect_list_delete' Autoupload.pk %}" class="btn btn-warning btn-sm">Delete</a>
      </td>
    </tr>
    {% endif %} {% endfor %}
  </tbody>
</table>

{% endblock %}

Main/templates/home.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DAP Security</title>
    <link rel="shortcut icon" href="../static/fav.ico" />
    {% comment %}
    <link rel="stylesheet" href="css/style.css" />
    {% endcomment %}
    <style>
      * {
        margin: 0;
        padding: 0;
        font-family: sans-serif;
      }
      .hero {
        width: 100%;
        height: 100vh;
        background-size: cover;
        background-position: center;
        position: relative;
        overflow: hidden;
      }

      button {
        color: #fbfcfd;
        padding: 10px 25px;
        background: transparent;
        border: 1px solid #fff;
        border-radius: 20px;
        outline: none;
        cursor: pointer;
      }
      .content {
        color: #fbfcfd;
        position: absolute;
        top: 50%;
        left: 8%;
        transform: translateY(-50%);
        z-index: 2;
      }
      #btn:hover {
        background-color: white;
        color: black;
      }
      h1 {
        font-size: 80px;
        margin: 10px 0 30px;
        line-height: 80px;
      }
      .side-bar {
        width: 50px;
        height: 100vh;
        background: linear-gradient(#00545d, #000729);
        position: absolute;
        right: 0;
        top: 0;
      }
      .menu {
        display: block;
        width: 25px;
        margin: 40px auto 0;
        cursor: pointer;
      }
      .useful-links img {
        width: 25px;
        margin: 5px auto;
        cursor: pointer;
      }

      .useful-links {
        width: 50px;
        text-align: center;
        position: absolute;
        bottom: 30px;
      }
      /* side navbar */
      .sidenav {
        height: 100%;
        width: 0;
        position: fixed;
        z-index: 1;
        top: 0;
        right: 0;
        background-color: #111;
        overflow-x: hidden;
        padding-top: 60px;
        transition: 0.5s;
      }

      .sidenav a {
        padding: 8px 8px 8px 32px;
        text-decoration: none;
        font-size: 25px;
        color: #818181;
        display: block;
        transition: 0.3s;
      }

      .sidenav a:hover {
        color: #f1f1f1;
      }

      .sidenav .closebtn {
        position: absolute;
        top: 25px;
        right: 12px;
        font-size: 36px;
        margin-left: 50px;
      }

      #main {
        transition: margin-left 0.5s;
        padding: 20px;
      }

      @media screen and (max-height: 450px) {
        .sidenav {
          padding-top: 15px;
        }
        .sidenav a {
          font-size: 18px;
        }
      }
    </style>
  </head>
  <body>
    <div class="hero">
      <video id="background-video" autoplay loop muted>
        <source src="../static/video.mp4" type="video/mp4" />
      </video>
      <div class="content">
        <small>Welcome to our</small>
        <h1>DAP<br />Security</h1>
      </div>
      <div class="side-bar">
        <a onclick="openNav()"><img src="../static/menu.png" class="menu" /></a>

        <div class="useful-links">
          <a onclick="copyLink()"><img src="../static/share.png" /></a>
          <a onclick="alert('만든이: 최용준, 김다혁, 원주현, 허현, 이진욱, 김용훈')"><img src="../static/info.png" /></a>
        </div>
      </div>
    </div>
    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="{% url 'connect' %}" style="text-decoration: none">취약점진단[자동]</a>
      <a href="{% url 'connect_list' %}" style="text-decoration: none">취약점진단[자동확인]</a>
      <a href="{% url 'diagnosis' %}" style="text-decoration: none">취약점진단[수동]</a>
      <a href="{% url 'model_form_upload' %}" style="text-decoration: none">취약점진단[수동진행]</a>
      <a href="{% url 'model_form' %}" style="text-decoration: none">취약점진단[수동확인]</a>
      <a href="{% url 'board' %}" style="text-decoration: none">게시판</a>
      <br /><br />

      {% if user.is_authenticated %}
      <a style="font-size: 1.6rem" style="text-decoration: none" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
      {% else %}
      <a style="font-size: 1.6rem" style="text-decoration: none" href="{% url 'common:login' %}">로그인</a>
      {% endif %} {% if not user.is_authenticated %}
      <a style="font-size: 1.6rem" style="text-decoration: none" href="{% url 'common:signup' %}">회원가입</a>
      {% endif %}
    </div>

    <script>
      function openNav() {
        document.getElementById("mySidenav").style.width = "300px";
      }

      function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
      }
    </script>
    <script>
      function copyLink() {
        // 현재 링크 가져오기
        var link = window.location.href;

        // 링크 복사하기
        var tempInput = document.createElement("input");
        tempInput.value = link;
        document.body.appendChild(tempInput);
        tempInput.select();
        document.execCommand("copy");
        document.body.removeChild(tempInput);

        // 메시지 표시
        alert("링크가 복사되었습니다.");
      }
    </script>
  </body>
</html>

Main/templates/my_view.html
{% extends 'base.html' %} {% load static %} {% block content %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="mb-3">
    제목 : <textarea name="title"></textarea>
    <button type="submit" class="btn btn-primary">Upload</button>
  </div>
</form>
<br />
{% endblock %}

Main/templates/question_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container my-3">
  <!-- message 표시 -->
  {% if messages %}
  <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
    <strong>{{ message.tags }}</strong>
    <ul>
      <li>{{ message.message }}</li>
    </ul>
    {% endfor %}
  </div>
  {% endif %}
  <!-- 질문 -->
  <h2 class="border-bottom py-2">{{ question.subject }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line">{{ question.content }}</div>
      <div class="d-flex justify-content-end">
        {% if question.modify_date %}
        <div class="badge bg-light text-dark p-2 text-start mx-3">
          <div class="mb-2">수정된 날짜</div>
          <div>{{ question.modify_date }}</div>
        </div>
        {% endif %}
        <div class="badge bg-light text-dark p-2 text-start">
          <div class="mb-2">{{ question.author.username }}</div>
          <div>{{ question.create_date }}</div>
        </div>
      </div>
      <div class="my-3">
        {% if request.user == question.author %}
        <a href="{% url 'question_modify' question.id  %}" class="btn btn-sm btn-outline-secondary">수정</a>
        <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'question_delete' question.id  %}">삭제</a>
        {% endif %}
      </div>
    </div>
  </div>

  <!-- 답변 -->
  <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
  {% for answer in question.answer_set.all %}
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line">{{ answer.content }}</div>
      <div class="d-flex justify-content-end">
        {% if question.modify_date %}
        <div class="badge bg-light text-dark p-2 text-start mx-3">
          <div class="mb-2">수정된 날짜</div>
          <div>{{ answer.modify_date }}</div>
        </div>
        {% endif %}
        <div class="badge bg-light text-dark p-2 text-start">
          <div class="mb-2">{{ answer.author.username }}</div>
          <div>{{ answer.create_date }}</div>
        </div>
      </div>
      <div class="my-3">
        {% if request.user == answer.author %}
        <a href="{% url 'answer_modify' answer.id  %}" class="btn btn-sm btn-outline-secondary">수정</a>
        <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'answer_delete' answer.id  %}">삭제</a>
        {% endif %}
      </div>
    </div>
  </div>
  <div>
    <div>
      {% endfor %}
      <!-- 답변 등록 -->
      <form action="{% url 'answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}

        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          {% for field in form %} {% if field.errors %}
          <div>
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
          </div>
          {% endif %} {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->

        <div class="mb-3">
          <label for="content" class="form-label">답변내용</label>
          <textarea {% if not user.is_authenticated %} disabled {% endif %} name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary" />
      </form>
    </div>
    {% endblock %}
  </div>
</div>

Main/templates/question_list.html
{% extends 'base.html' %} {% load list_filter %} {% block content %}

<div class="container my-3">
  <table class="table">
    <thead>
      <tr class="text-center table-dark">
        <th>번호</th>
        <th style="width: 50%">제목</th>
        <th>글쓴이</th>
        <th>작성일시</th>
      </tr>
    </thead>
    <tbody>
      {% if question_list %} {% for question in question_list %}
      <tr class="text-center">
        <td>
          <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
          {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
        </td>
        <td class="text-start">
          <a href="{% url 'detail' question.id %}">{{ question.subject }}</a>
          {% if question.answer_set.count > 0 %}
          <span class="text-danger small mx-2">{{ question.answer_set.count }}개의 답변</span>
          {% endif %}
        </td>
        <td>{{ question.author.username }}</td>
        <!-- 글쓴이 추가 -->
        <td>{{ question.create_date }}</td>
      </tr>
      {% endfor %} {% else %}
      <tr>
        <td colspan="4">질문이 없습니다.</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
  <!-- 페이징처리 시작 -->
  <ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if question_list.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in question_list.paginator.page_range %}
    <!-- {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}  -->
    {% if page_number == question_list.number %}
    <li class="page-item active" aria-current="page">
      <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% endif %}
    <!-- {% endif %} -->
    {% endfor %}
    <!-- 다음페이지 -->
    {% if question_list.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
  </ul>
  <!-- 페이징처리 끝 -->
  <a href="{% url 'question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>

{% endblock %}